### ISSUE TITLE
Rewrite on Python?

### ISSUE THREAD

**Issue by fearocanity** [fearocanity/ebtrfio-hooks#3]
This change aims to:

- Fully rewrite on Python
- Have better Commands
- Higher the reliability
- Have Faster Response
- Work without Webhooks (Purposely relying on API)

**Comment by Nandini1071** [comment]
Hi @fearocanity is this issue still open, if yes then what is the requirement would like to contribute on this.

**Comment by fearocanity** [comment]
> Hi @fearocanity is this issue still open, if yes then what is the requirement would like to contribute on this.

Requirement? Nothing! And yes, this issue is OPEN!
If we ever wrote the backbone of this script on the newbranch I would create, maybe you can help us port the script and fix bugs, also in debugging.

Thank you!

**Comment by fearocanity** [comment]
This would be moved on other repository.

**Comment by Nandini1071** [comment]
Ok so on which I can help you in python side ?

**Comment by fearocanity** [comment]
> Ok so on which I can help you in python side ?

I'm still planning and formulating an idea on how do we create it. *(For now)*
My idea is creating a file tree like this:
```bash
* handler
    |---- __init__.py
    |---- handler.py (handle arguments from comments)
    |---- getComments.py
    |---- (etc... and so on)

* commands
    |---- __init__.py
    |---- addText.py (consist of functions that is related to it.)
    |---- (etc... and so on)
```

Or just creating a class.

So we can just import it like it was acting library in the `main`.

### Visualization / Pseudo-code
This type of commenting format is Google-style. Maybe after wrapping up the code, the final product should look like this.
```python
class ImageEditors:
    def addText(self, text: str, coords: tuple[int, int]) -> bool:
        """
        Add text to image.

        Args:
            text (str): Text to add in the image.
            coords (tuple[int, int]): Coordinates in the format (x, y).

        Returns:
            bool: True if it is successfully applied in `temp.jpg`, False otherwise.
        """
        # rest of the code
        pass

    def otherFunction(self, ...):
        # rest of the code
        pass
```
----
I can't still have the schedule to start or create it. I'm still busy with schoolwork.😅
BTW, you could suggest too or should we move on Discord?

**Comment by Nandini1071** [comment]
oh ok, but I am having some doubts like:
1. what is the product which you are planning to create like you mention word "Comments" from where you will be getting those and what you want to do with them.
2. what is the main goal or project after knowing this would be able to suggest some ideas or would start implementation.

**Comment by fearocanity** [comment]
> oh ok, but I am having some doubts like:
> 
> 1. what is the product which you are planning to create like you mention word "Comments" from where you will be getting those and what you want to do with them.
> 2. what is the main goal or project after knowing this would be able to suggest some ideas or would start implementation.

Sorry, I didn't said it first.

Goal of it is to get comments from facebook posts, and sent back the image with modifications (based on the arguments presented/requested). We're using `Facebook Graph API`.
- gets comments (also the `comment_id`) from fb post with prefix that triggers the bot (i.e `!req`)
- the command must have `-e [eps]`, `-f [frame]` (required arguments). to get the specific image, each episode has frames (images). image stored somewhere (locally).
- takes arguments from comment, for example: `--addtext[text:"Hello World"]`, and something like `--append[frame:{50,60}]`, or maybe use `ImageMagick` command-line arrgument format.
- apply the changes to image
- sent back the modified image from where the comment got from (as a reply).

Thats it. To put it simple, it works just like the bots from Discord, but on Facebook.
Reason? Effeciency for users... (creating memes? possibly)

**Comment by Nandini1071** [comment]
Oh ok got the idea so the implementation would be in python right ?
And when are you planning to start this ?

**Comment by fearocanity** [comment]
> Oh ok got the idea so the implementation would be in python right ? And when are you planning to start this ?

I'll notify you, If I wrote the backbone of the script. Since my schedule is kind of cramped up.😅

**Comment by Nandini1071** [comment]
What script, I mean let me know If I can help you on this ? @fearocanity
